### ISSUE TITLE
Cannot find module gensync\index.js

### ISSUE THREAD

**Issue by zcrkey** [loganfsmyth/gensync#15]
Cannot find module 'xxx\xxx\node_modules\gensync\index.js'

It is not found in the gensync directory index.js

![image](https://user-images.githubusercontent.com/39945923/99532670-a0f83900-29df-11eb-83e1-6dba563da638.png)

**Comment by loganfsmyth** [comment]
Sounds like maybe your `npm install` failed? That file definitely exists.

**Comment by zcrkey** [comment]
Yes, I found that my NPM installation failed to cause this problem

thank! @loganfsmyth
