### ISSUE TITLE
sync() function call error!

### ISSUE THREAD

**Issue by z284949127** [loganfsmyth/gensync#30]
gensync=require('gensync')
as=async()=>new Promise(r=>setTimeout(()=>r(99),1000))
gensync(as).sync()

**it trhow error like below, what's wrong?**

Uncaught TypeError: gen.next is not a function
    at evaluateSync (D:\work\gitee\belt-road\logs\2022-05-23\java-web-2022-05-23-2115\node_modules\gensync\index.js:251:28)
    at Function.sync (D:\work\gitee\belt-road\logs\2022-05-23\java-web-2022-05-23-2115\node_modules\gensync\index.js:89:14)

**Comment by loganfsmyth** [comment]
`gensync` should be passed a genrator function, not an async function.

**Comment by z284949127** [comment]
**Thank you a lot!
I found another way to implament during last night, depens on deasync:**

```javascript
const deasync = require('deasync')
/**
 * 异步转同步
 * 
 * 使用方法：
 * let as=(a,b,c)=>new Promise((r,j)=>setTimeout(()=>{console.log(a,b,c);r(99);},500))
 * let sync=fun.wrapSync(as)
 * let res=sync(1,2,3)
 * console.log(res)
 * let asj=(a,b,c)=>new Promise((r,j)=>setTimeout(()=>{console.log(a,b,c);j(99);},500))
 * let syncj=fun.wrapSync(asj)
 * try{
 *    let res=syncj(1,2,3)
 * }catch(e){
 *   console.log(e)
 * }
 * 
 * 依赖：
 * deasync
 * 
 * 引用：
 * 使用了deasync，用到了他的sleep方法(https://github.com/abbr/deasync);
 * 使用了function-wrapper，用到了他的wrap方法(https://github.com/klny/function-wrapper/blob/master/src/wrapper.js);
 * 
 * @param { Function } asFun async函数
 * @returns { Function } 同步函数
 * @see <a href="https://www.npmjs.com/package/deasync">deasync</a>
 * @see <a href="https://www.npmjs.com/package/function-wrapper">function-wrapper</a>
 * @see <a href="https://cloud.tencent.com/developer/article/1419802">JS异步转同步组件——DeAsync.js原理深入分析</a>
 * @see <a href="https://blog.csdn.net/qq_37530404/article/details/85232471">JavaScript 中 Apply 和 Call 的含义与区别</a>
 * @author mmbro
 * @version 1.0.0
 * @since 2022-5-26 21:47:56
 */
fun.wrapSync = (asFun) => {
    return function () {
        let state = 0, result;
        asFun.apply(this, arguments).then(res => {
            result = res, state = 1;
        }).catch(err => {
            result = err, state = 2;
        })
        while (!state) {
            deasync.sleep(100)
        }
        if (state === 1) {
            return result
        } else {
            throw result
        }
    }
}
```

**Comment by loganfsmyth** [comment]
Keep in mind that `deasync` works by forcing the code to execute in a way that is inconsistent with the JS spec and I'd consider using it in anything but a toy project to be a mistake and something you'll likely regret!

**Comment by z284949127** [comment]
**so do i think.** In this case, is there any other way to implement the ```deasync.sleep(100)``` method? For example, in cmd, you can use ```ping -n 30 127.0.0.1 > null``` to implement sleep

**Comment by loganfsmyth** [comment]
It is hard to say without knowing why your code needs to be synchronous in the first place. I'd expect you to have a sleep function that returns a promise, and the code that needs to be delayed would would `await` the promise to cause itself to suspend for however long you've told it to.
