### ISSUE TITLE
TypeError is thrown on V8 --harmony_tailcalls

### ISSUE THREAD

**Issue by JLHwung** [loganfsmyth/gensync#4]
**Reproduction**

Create a `test.js` alongside with `index.js`
```js
var gensync = require("./index.js");
const isAsync = gensync({ sync: () => false, errback: cb => cb(null, true) });
const gen = (function*() { var async = yield * isAsync(); })();
gen.next();
console.log(gen.next().done);
```
Run this snippet with node.js 6
```
node --harmony_tailcalls test.js
```
**Expected**
Print `true`.

**Actual**
```
TypeError: Iterator result false is not an object
    at /path/to/gensync/test.js:3:48
    at next (native)
    at Object.<anonymous> (/path/to/gensync/test.js:5:17)
```

Among the other major implementors, only Safari supports TCO and I could not reproduce this issue on Safari. Therefore it is probably a platform-specific issue and thus, ideally, should be fixed on V8's side.

However Tail Call Optimization has been removed in V8 since node.js 8, so I don't think this issue should be prioritized.

**Additional Context**
This issue was initially reported at https://github.com/babel/babel/issues/11226.

**Comment by jridgewell** [comment]
This was kind of fun to look into. It can be reduced down to just:

```js
"use strict";

function* isAsync() {
  const sync = () => false;
  return sync();
};

function* gen() {
  yield* isAsync();
}

for (const i of gen()) {}
```

The fix is just to break any tail calls inside generators.
